SET PATH=C:\Software\Keil_v5\ARM\ARMCC\Bin;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Software\Perl64\site\bin;C:\Software\Perl64\bin;C:\Software\Python36\Scripts\;C:\Software\Python36\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;c:\Program Files\TortoiseSVN\bin;c:\Program Files\PuTTY\;C:\Program Files\FEBioStudio\febio;C:\Program Files (x86)\WinSCP;C:\Program Files\Git\cmd;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\Microsoft VS Code\bin;C:\Users\m6lyu\AppData\Local\Microsoft\WindowsApps;
SET CPU_TYPE=LPC1768
SET CPU_VENDOR=NXP
SET UV2_TARGET=AE Lib RAM
SET CPU_CLOCK=0x00B71B00
"C:\Software\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae.__i"
"C:\Software\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae_tasks.__i"
"C:\Software\Keil_v5\ARM\ARMCC\Bin\ArmAr" --Via ".\Objects\RAM\ArInp.Scr"
